NAME = fftools
DESC = FFmpeg tools library

HEADERS = fftools.h       \
          version.h       \
          version_major.h \

OBJS = ffmpeg_dec.o        \
       ffmpeg_demux.o      \
       ffmpeg_enc.o        \
       ffmpeg_filter.o     \
       ffmpeg_hw.o         \
       ffmpeg_mux.o        \
       ffmpeg_mux_init.o   \
       ffmpeg_opt.o        \
       ffmpeg_sched.o      \
       ffmpeg.o            \
       cmdutils.o          \
       objpool.o           \
       opt_common.o        \
       sync_queue.o        \
       thread_queue.o      \
       fftools.o           \
       version.o           \
