NAME = fftools
DESC = FFmpeg tools library

HEADERS = fftools.h       \
          version.h       \
          version_major.h \

OBJS = cmdutils.o        \
       ffmpeg.o          \
       ffmpeg_filter.o   \
       ffmpeg_hw.o       \
       ffmpeg_mux.o      \
       ffmpeg_opt.o      \
       opt_common.o      \
       version.o         \
       fftools.o         \
